# Generated by Django 3.2 on 2024-06-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240616_0144'),
        ('reviews', '0004_alter_review_unique_together'),
    ]

    operations = [
    ]
